/*
 * Kirin Tor waycrystals: an FFXIV-style aetheryte network.
 *
 * - A waycrystal floats next to every inn and flight master of the four continents (spawned by
 *   data/sql/db-world/2026_09_25_01_waystones.sql, generated by tools/make_waystones.py).
 * - Walking up to a crystal (or talking to it) attunes the character to it; attunement is permanent
 *   (characters.character_waystone).
 * - Talking to any crystal offers a translocation to every attuned crystal.
 * - The KirinTorWaystones client addon draws the crystals on the world map and asks for a
 *   translocation from anywhere by clicking one (addon messages with prefix "KTWS").
 *
 * Translocation is the plugin's own spell: data/patches.json adds a 5 s copy of spell 44080 ("Teleport: Zul'Aman
 * Instance") to the client and the server under an id given out when the patch was installed, and binds
 * spell_custom_translocation to it. Its teleport effect is replaced here, so movement, combat and damage
 * interrupt it like any cast.
 */

#include "Chat.h"
#include "Creature.h"
#include "DBCStores.h"
#include "DatabaseEnv.h"
#include "Group.h"
#include "Log.h"
#include "ObjectAccessor.h"
#include "Player.h"
#include "ScriptMgr.h"
#include "ScriptedCreature.h"
#include "ScriptedGossip.h"
#include "SpellInfo.h"
#include "SpellMgr.h"
#include "SpellScript.h"
#include "SpellScriptLoader.h"
#include "WorldPacket.h"
#include "WorldSession.h"

#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <map>
#include <mutex>
#include <set>
#include <unordered_map>

namespace
{
    // Keep in sync with tools/make_waystones.py
    constexpr uint32 NPC_WAYSTONE = 9100001;
    constexpr ObjectGuid::LowType WAYSTONE_GUID_BASE = 9100000;
    constexpr float ATTUNE_DISTANCE = 15.0f;
    constexpr char const* ADDON_PREFIX = "KTWS";
    constexpr uint32 ZONES_PER_PAGE = 20;

    // The id of the Translocation spell (world.plugin_ids), 0 while the plugin's patches are not installed.
    uint32 TranslocationSpell()
    {
        static uint32 const id = []
        {
            QueryResult r = WorldDatabase.Query("SELECT `id` FROM `plugin_ids` WHERE `plugin` = 'lonelyice.waystones' AND `name` = 'translocation'");
            uint32 v = r ? r->Fetch()[0].Get<uint32>() : 0;
            if (!v)
                LOG_ERROR("module", "lonelyice.waystones: no id for the Translocation spell, its patches are not installed");
            return v;
        }();
        return id;
    }

    enum GossipSender : uint32
    {
        SENDER_ROOT      = 1,
        SENDER_CONTINENT = 2,   // action = continent | page << 16
        SENDER_ZONE      = 3,   // action = zone
        SENDER_WAYSTONE  = 4,   // action = waystone id
    };

    // WorldMapArea ids of the continent maps, in menu order
    struct Continent { uint32 id; char const* en; char const* ru; };
    constexpr Continent CONTINENTS[] = {
        { 14,  "Eastern Kingdoms", "Восточные королевства" },
        { 13,  "Kalimdor",         "Калимдор" },
        { 466, "Outland",          "Запределье" },
        { 485, "Northrend",        "Нордскол" },
    };

    struct Waystone
    {
        uint32 id;
        uint32 map;
        uint32 zone;
        uint32 continent;
        float x, y, z, o;
        std::string name[2];     // 0 = en, 1 = ru
        std::string zoneName[2];
    };

    // sWaystones is only written at startup. The per-player maps are touched from map update
    // threads (creature AI, spells) and session updates, hence the lock.
    std::map<uint32, Waystone> sWaystones;
    std::mutex sPlayerLock;
    std::unordered_map<ObjectGuid::LowType, std::set<uint32>> sAttuned;
    std::unordered_map<ObjectGuid::LowType, uint32> sPendingTranslocation;

    bool IsRealPlayer(Player const* player)
    {
        return player && player->GetSession() && !player->GetSession()->IsBot();
    }

    int Lang(Player const* player)
    {
        return player->GetSession()->GetSessionDbcLocale() == LOCALE_ruRU ? 1 : 0;
    }

    char const* Text(Player const* player, char const* en, char const* ru)
    {
        return Lang(player) ? ru : en;
    }

    void Notify(Player* player, std::string const& text)
    {
        ChatHandler(player->GetSession()).SendSysMessage("|cffb48cff" + text + "|r");
    }

    Waystone const* GetWaystone(uint32 id)
    {
        auto itr = sWaystones.find(id);
        return itr != sWaystones.end() ? &itr->second : nullptr;
    }

    uint32 WaystoneIdOf(Creature const* creature)
    {
        ObjectGuid::LowType const spawnId = creature->GetSpawnId();
        return spawnId > WAYSTONE_GUID_BASE ? uint32(spawnId - WAYSTONE_GUID_BASE) : 0;
    }

    bool IsAttuned(Player const* player, uint32 id)
    {
        std::lock_guard<std::mutex> guard(sPlayerLock);
        auto itr = sAttuned.find(player->GetGUID().GetCounter());
        return itr != sAttuned.end() && itr->second.count(id);
    }

    // State for the addon: hex string, bit (id - 1) set when attuned
    void SendAddonState(Player* player)
    {
        if (!IsRealPlayer(player) || sWaystones.empty())
            return;

        uint32 const maxId = sWaystones.rbegin()->first;
        std::vector<uint8> nibbles((maxId + 3) / 4, 0);
        {
            std::lock_guard<std::mutex> guard(sPlayerLock);
            auto itr = sAttuned.find(player->GetGUID().GetCounter());
            if (itr != sAttuned.end())
                for (uint32 id : itr->second)
                    if (id >= 1 && id <= maxId)
                        nibbles[(id - 1) / 4] |= 1 << ((id - 1) % 4);
        }

        std::string hex;
        for (uint8 nibble : nibbles)
            hex += "0123456789abcdef"[nibble];

        std::string const wire = std::string(ADDON_PREFIX) + "\tS\t" + hex;
        WorldPacket data;
        ChatHandler::BuildChatPacket(data, CHAT_MSG_WHISPER, LANG_ADDON, player, player, wire);
        player->SendDirectMessage(&data);
    }

    void Attune(Player* player, uint32 id)
    {
        Waystone const* waystone = GetWaystone(id);
        if (!waystone || !IsRealPlayer(player))
            return;

        ObjectGuid::LowType const guid = player->GetGUID().GetCounter();
        {
            std::lock_guard<std::mutex> guard(sPlayerLock);
            if (!sAttuned[guid].insert(id).second)
                return;
        }
        CharacterDatabase.Execute("INSERT IGNORE INTO `character_waystone` (`guid`, `waystone`) VALUES ({}, {})", guid, id);

        Notify(player, Acore::StringFormat(Text(player, "Waycrystal attuned: {}.", "Путевой кристалл настроен: {}."),
            waystone->name[Lang(player)]));
        SendAddonState(player);
    }

    void StartTranslocation(Player* player, uint32 id)
    {
        Waystone const* waystone = GetWaystone(id);
        if (!waystone || !IsAttuned(player, id))
        {
            Notify(player, Text(player, "You are not attuned to that waycrystal.", "Вы не настроены на этот кристалл."));
            return;
        }

        if (!player->IsAlive() || player->IsInFlight())
            return;

        if (player->GetMap()->Instanceable())
        {
            Notify(player, Text(player, "The waycrystal network cannot reach you here.", "Здесь сеть кристаллов недоступна."));
            return;
        }

        if (player->IsInCombat())
        {
            Notify(player, Text(player, "You cannot translocate while in combat.", "Нельзя переместиться во время боя."));
            return;
        }

        if (player->IsMounted())
        {
            if (player->IsFlying())
            {
                Notify(player, Text(player, "Land first.", "Сначала приземлитесь."));
                return;
            }
            player->Dismount();
            player->RemoveAurasByType(SPELL_AURA_MOUNTED);
        }

        {
            std::lock_guard<std::mutex> guard(sPlayerLock);
            sPendingTranslocation[player->GetGUID().GetCounter()] = id;
        }
        player->CastSpell(player, TranslocationSpell(), false);
    }

    void SendAddon(Player* player, std::string const& body)
    {
        std::string const wire = std::string(ADDON_PREFIX) + "\t" + body;
        WorldPacket data;
        ChatHandler::BuildChatPacket(data, CHAT_MSG_WHISPER, LANG_ADDON, player, player, wire);
        player->SendDirectMessage(&data);
    }

    // Someone of the group translocated to `w`: bots come along, real players attuned to the same crystal
    // get an offer (addon popup, "OFFER\t<id>\t<name>"; accepting is a normal "TP" request with its cast).
    // Runs inside the traveller's map update; MapUpdate.Threads = 1 keeps touching other members safe.
    void OfferGroup(Player* traveller, Waystone const& w)
    {
        Group* group = traveller->GetGroup();
        if (!group)
            return;

        uint32 botIndex = 0;
        for (GroupReference* ref = group->GetFirstMember(); ref; ref = ref->next())
        {
            Player* member = ref->GetSource();
            if (!member || member == traveller || !member->IsInWorld() || !member->GetSession())
                continue;

            if (member->GetSession()->IsBot())
            {
                if (!member->IsAlive() || member->IsInCombat() || member->IsInFlight() || member->GetMap()->Instanceable())
                    continue;
                // Arrive a moment after the traveller, spread in a small ring around the crystal's landing spot
                float const angle = w.o + float(M_PI) * (0.6f + 0.35f * float(botIndex++));
                float const x = w.x + 2.5f * std::cos(angle);
                float const y = w.y + 2.5f * std::sin(angle);
                ObjectGuid const guid = member->GetGUID();
                member->m_Events.AddEventAtOffset([guid, w, x, y]()
                {
                    Player* bot = ObjectAccessor::FindPlayer(guid);
                    if (bot && bot->IsAlive() && !bot->IsInCombat() && !bot->IsInFlight())
                        bot->TeleportTo(w.map, x, y, w.z, w.o);
                }, 1500ms);
                continue;
            }

            if (!IsAttuned(member, w.id))
                continue;
            if (member->GetMapId() == w.map && member->GetDistance(w.x, w.y, w.z) < 100.0f)
                continue;   // already there

            // The addon shows it as a centred confirmation popup; no chat line
            SendAddon(member,Acore::StringFormat("OFFER\t{}\t{}", w.id, traveller->GetName()));
        }
    }

    void LoadWaystones()
    {
        sWaystones.clear();
        QueryResult result = WorldDatabase.Query(
            "SELECT `id`, `map`, `zone`, `continent`, `x`, `y`, `z`, `o`, `name_en`, `name_ru`, `zone_en`, `zone_ru` FROM `custom_waystone`");
        if (!result)
        {
            LOG_WARN("server.loading", ">> Loaded 0 waycrystals (custom_waystone is empty)");
            return;
        }

        do
        {
            Field* f = result->Fetch();
            Waystone w;
            w.id = f[0].Get<uint32>();
            w.map = f[1].Get<uint32>();
            w.zone = f[2].Get<uint32>();
            w.continent = f[3].Get<uint32>();
            w.x = f[4].Get<float>();
            w.y = f[5].Get<float>();
            w.z = f[6].Get<float>();
            w.o = f[7].Get<float>();
            w.name[0] = f[8].Get<std::string>();
            w.name[1] = f[9].Get<std::string>();
            w.zoneName[0] = f[10].Get<std::string>();
            w.zoneName[1] = f[11].Get<std::string>();
            sWaystones[w.id] = std::move(w);
        } while (result->NextRow());

        LOG_INFO("server.loading", ">> Loaded {} waycrystals", sWaystones.size());
    }

    // ------------------------------------------------------------------------------ gossip menus
    std::vector<Waystone const*> AttunedWaystones(Player const* player, uint32 excludeId)
    {
        std::vector<Waystone const*> list;
        std::lock_guard<std::mutex> guard(sPlayerLock);
        auto itr = sAttuned.find(player->GetGUID().GetCounter());
        if (itr != sAttuned.end())
            for (uint32 id : itr->second)
                if (id != excludeId)
                    if (Waystone const* w = GetWaystone(id))
                        list.push_back(w);
        return list;
    }

    void ShowRoot(Player* player, Creature* creature)
    {
        ClearGossipMenuFor(player);
        uint32 const here = WaystoneIdOf(creature);
        auto const attuned = AttunedWaystones(player, here);
        int const lang = Lang(player);

        for (Continent const& continent : CONTINENTS)
        {
            size_t const count = std::count_if(attuned.begin(), attuned.end(),
                [&](Waystone const* w) { return w->continent == continent.id; });
            if (count)
                AddGossipItemFor(player, GOSSIP_ICON_TAXI,
                    Acore::StringFormat("{} ({})", lang ? continent.ru : continent.en, count), SENDER_CONTINENT, continent.id);
        }

        if (attuned.empty())
            AddGossipItemFor(player, GOSSIP_ICON_CHAT, Text(player,
                "Touch other waycrystals on your travels to translocate to them.",
                "Касайтесь других кристаллов в пути, чтобы перемещаться к ним."), SENDER_ROOT, 0);

        SendGossipMenuFor(player, NPC_WAYSTONE, creature);
    }

    void ShowContinent(Player* player, Creature* creature, uint32 continent, uint32 page)
    {
        ClearGossipMenuFor(player);
        int const lang = Lang(player);

        // zone -> localized name, sorted by name
        std::map<uint32, std::string> zones;
        for (Waystone const* w : AttunedWaystones(player, WaystoneIdOf(creature)))
            if (w->continent == continent)
                zones[w->zone] = w->zoneName[lang];

        std::vector<std::pair<uint32, std::string>> sorted(zones.begin(), zones.end());
        std::sort(sorted.begin(), sorted.end(), [](auto const& a, auto const& b) { return a.second < b.second; });

        uint32 const first = page * ZONES_PER_PAGE;
        for (uint32 i = first; i < sorted.size() && i < first + ZONES_PER_PAGE; ++i)
            AddGossipItemFor(player, GOSSIP_ICON_TAXI, sorted[i].second, SENDER_ZONE, sorted[i].first);

        if (sorted.size() > first + ZONES_PER_PAGE)
            AddGossipItemFor(player, GOSSIP_ICON_CHAT, Text(player, "More...", "Дальше..."), SENDER_CONTINENT,
                continent | ((page + 1) << 16));

        AddGossipItemFor(player, GOSSIP_ICON_CHAT, Text(player, "Back", "Назад"), SENDER_ROOT, 0);
        SendGossipMenuFor(player, NPC_WAYSTONE, creature);
    }

    void ShowZone(Player* player, Creature* creature, uint32 zone)
    {
        ClearGossipMenuFor(player);
        int const lang = Lang(player);

        std::vector<Waystone const*> list;
        uint32 continent = 0;
        for (Waystone const* w : AttunedWaystones(player, WaystoneIdOf(creature)))
            if (w->zone == zone)
            {
                list.push_back(w);
                continent = w->continent;
            }

        std::sort(list.begin(), list.end(), [lang](Waystone const* a, Waystone const* b) { return a->name[lang] < b->name[lang]; });
        for (Waystone const* w : list)
            AddGossipItemFor(player, GOSSIP_ICON_TAXI, w->name[lang], SENDER_WAYSTONE, w->id);

        AddGossipItemFor(player, GOSSIP_ICON_CHAT, Text(player, "Back", "Назад"), SENDER_CONTINENT, continent);
        SendGossipMenuFor(player, NPC_WAYSTONE, creature);
    }
}

class npc_custom_waystone : public CreatureScript
{
public:
    npc_custom_waystone() : CreatureScript("npc_custom_waystone") { }

    struct npc_custom_waystoneAI : public ScriptedAI
    {
        npc_custom_waystoneAI(Creature* creature) : ScriptedAI(creature) { }

        void MoveInLineOfSight(Unit* who) override
        {
            Player* player = who->ToPlayer();
            if (player && IsRealPlayer(player) && me->IsWithinDistInMap(player, ATTUNE_DISTANCE))
                Attune(player, WaystoneIdOf(me));
        }

        void AttackStart(Unit* /*who*/) override { }
        void UpdateAI(uint32 /*diff*/) override { }
    };

    bool OnGossipHello(Player* player, Creature* creature) override
    {
        Attune(player, WaystoneIdOf(creature));
        ShowRoot(player, creature);
        return true;
    }

    bool OnGossipSelect(Player* player, Creature* creature, uint32 sender, uint32 action) override
    {
        switch (sender)
        {
            case SENDER_CONTINENT:
                ShowContinent(player, creature, action & 0xFFFF, action >> 16);
                break;
            case SENDER_ZONE:
                ShowZone(player, creature, action);
                break;
            case SENDER_WAYSTONE:
                CloseGossipMenuFor(player);
                StartTranslocation(player, action);
                break;
            default:
                ShowRoot(player, creature);
                break;
        }
        return true;
    }

    CreatureAI* GetAI(Creature* creature) const override
    {
        return new npc_custom_waystoneAI(creature);
    }
};

class spell_custom_translocation : public SpellScript
{
    PrepareSpellScript(spell_custom_translocation);

    void HandleTeleport(SpellEffIndex effIndex)
    {
        PreventHitDefaultEffect(effIndex);

        Player* player = GetHitUnit() ? GetHitUnit()->ToPlayer() : nullptr;
        if (!player)
            return;

        uint32 id = 0;
        {
            std::lock_guard<std::mutex> guard(sPlayerLock);
            auto itr = sPendingTranslocation.find(player->GetGUID().GetCounter());
            if (itr == sPendingTranslocation.end())
                return;
            id = itr->second;
            sPendingTranslocation.erase(itr);
        }

        if (Waystone const* w = GetWaystone(id))
            if (IsAttuned(player, id))
            {
                OfferGroup(player, *w);
                player->TeleportTo(w->map, w->x, w->y, w->z, w->o);
            }
    }

    void HandleScript(SpellEffIndex effIndex)
    {
        PreventHitDefaultEffect(effIndex);
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(spell_custom_translocation::HandleTeleport, EFFECT_0, SPELL_EFFECT_TELEPORT_UNITS);
        OnEffectHitTarget += SpellEffectFn(spell_custom_translocation::HandleScript, EFFECT_1, SPELL_EFFECT_SCRIPT_EFFECT);
    }
};

class CustomWaystonesWorldScript : public WorldScript
{
public:
    CustomWaystonesWorldScript() : WorldScript("CustomWaystonesWorldScript", { WORLDHOOK_ON_STARTUP }) { }

    void OnStartup() override
    {
        LoadWaystones();
        TranslocationSpell();
    }
};

class CustomWaystonesPlayerScript : public PlayerScript
{
public:
    CustomWaystonesPlayerScript() : PlayerScript("CustomWaystonesPlayerScript",
        { PLAYERHOOK_ON_LOGIN, PLAYERHOOK_ON_LOGOUT, PLAYERHOOK_CAN_PLAYER_USE_PRIVATE_CHAT }) { }

    void OnPlayerLogin(Player* player) override
    {
        if (!IsRealPlayer(player))
            return;

        ObjectGuid::LowType const guid = player->GetGUID().GetCounter();
        std::set<uint32> attuned;
        if (QueryResult result = CharacterDatabase.Query("SELECT `waystone` FROM `character_waystone` WHERE `guid` = {}", guid))
            do
                attuned.insert(result->Fetch()[0].Get<uint32>());
            while (result->NextRow());

        std::lock_guard<std::mutex> guard(sPlayerLock);
        sAttuned[guid] = std::move(attuned);
    }

    void OnPlayerLogout(Player* player) override
    {
        ObjectGuid::LowType const guid = player->GetGUID().GetCounter();
        std::lock_guard<std::mutex> guard(sPlayerLock);
        sAttuned.erase(guid);
        sPendingTranslocation.erase(guid);
    }

    // Addon requests arrive as whispers to self: "KTWS\t<command>[\t<arg>]"
    bool OnPlayerCanUseChat(Player* player, uint32 /*type*/, uint32 lang, std::string& msg, Player* /*receiver*/) override
    {
        if (lang != LANG_ADDON || msg.compare(0, 5, "KTWS\t") != 0)
            return true;

        std::string const body = msg.substr(5);
        if (body == "SYNC")
            SendAddonState(player);
        else if (body.compare(0, 3, "TP\t") == 0)
            StartTranslocation(player, uint32(std::strtoul(body.c_str() + 3, nullptr, 10)));

        return false;
    }
};

void AddCustomWaystonesScripts()
{
    new npc_custom_waystone();
    RegisterSpellScript(spell_custom_translocation);
    new CustomWaystonesWorldScript();
    new CustomWaystonesPlayerScript();
}
